### ISSUE TITLE
Any possible to solve out the departure's and approach's Fix point?

### ISSUE THREAD

**Issue by dextercai** [Bokjan/BravoFinder#10]
Any possible to solve out the departure's and approach's Fix point?

**Comment by Bokjan** [comment]
Can you describe the problem more precisely? Cannot understand.

**Comment by dextercai** [comment]
My bad.  
Is there any way to display the departure or approach  way for the airport. Just like  AND11D for ZSPD's 17L/R. May be it can be described as displaying the airport's departure and approach way for the different runway.

**Comment by Bokjan** [comment]
I got it.

Let me check the code. I'll give you a detailed reply later.

**Comment by Bokjan** [comment]
That's easy, if you just want to print out available standard procedures after calculating.

Just simply declare some `vector`s (for keeping procedures and runways) in `Finder.hpp` (or other places you like) with `extern` storage class, then define these variables in a `.cpp` file (that means they will be complied into an object file). In `DataConverter.cpp`, around line 150 - 186, we parse the SIDSTAR file of the assigned airport. Open a SIDSTAR file and we find the procedure names follow word `SID` for departure procedures or `STAR` for arrival. You can find label `SID_LABEL` (line 152) and `STAR_LABEL` (line 175), they indicate starts of these two state machine. You just read a string (separated by spaces) immediately after a `SID` or `STAR` word and this string is the name of the procedure. Procedure names are followed by `RNY {Runway name}`, so, similarly, continue to read two strings, and the second one is the name of the runway.

After that, you successfully build some lists containing the information you need and you can print out it anywhere you want to.

**Comment by dextercai** [comment]
Thank you for your reply. I will try it later.
