### ISSUE TITLE
多cycle共存异常 | Malfunction with multiple cycle

### ISSUE THREAD

**Issue by ttsunboy** [Bokjan/BravoFinder#16]
使用WebAPI，同时放置了两个版本的cycle，config.json第二位的cycle查询返回`{"status":500,"msg":"cannot calculate a route"}`。

Using WebAPI with two cycles. The second cycle in config.json returns `{"status":500,"msg":"cannot calculate a route"}` on query.
***************
OS: CentOS 8 x64
Scaffold built with rpm version of RapidJSON

config.json:
```json
[
  {
    "cycle" : "AIRAC2004",
    "path" : "/root/nav/AIRAC2004"
  },
  {
    "cycle" : "NAIP1911",
    "path" : "/root/nav/NAIP1911"
  }
]
```

**Comment by ttsunboy** [comment]
尝试把异常`what()`了一下，显示`ZBAA vertex doesn't exist`。
……这怎么可能嘛！顺序反过来之后依然是第二位出错。

Tried to do `e.what()`, showed `ZBAA vertex doesn't exist`.
...just impossible. Still the second returns unexpected error after switching those two.

uri: /route/NAIP1911?dep=zbaa&arr=zspd

**Comment by Bokjan** [comment]
Thank you for opening this issue! Bug fixed: https://github.com/Bokjan/BravoFinder/commit/ec6ea65fddc3a432003479509542ab0aac82a2aa .

**Comment by ttsunboy** [comment]
现在变成第一个不能用了【沉思
路径都能找对，是不是`DataSet`附近的问题？
我试着捣鼓一下

Now it's the first that's unusable.
Paths to those nav data are correctly found, guessing if error near `DataSet`?
Maybe I can also do sth to spoil it (?

**Comment by Bokjan** [comment]
I forgot the constructor...
Try this: https://github.com/Bokjan/BravoFinder/commit/25e42eefb17f9c89a4e97e7bbb135783a7e33c58

**Comment by ttsunboy** [comment]
Perfect~

这样就不用再写后端了（？），靴靴大佬，顺便祝SINO的服务器早日修好
Thx it works now sooo good and wish you a good day (this is not a translation)

**Comment by Bokjan** [comment]
I strongly recommend that you should NOT directly use the `WebAPI`. Scaffold is a **single-worker**, **synchronized** framework, and has very poor performance. The library itself supports concurrency.

**Comment by ttsunboy** [comment]
谢谢dalao的建议，过几天<del>头发长出来一点之后</del>搞一个so进php。

说起来，有没有什么能够解决“台湾海峡直飞难题”的计算方法？
BTW is there a solution to DCT problems of Taiwan Straits?
