### ISSUE TITLE
does this project design for linux?

### ISSUE THREAD

**Issue by dextercai** [Bokjan/BravoFinder#9]
l try to compile it on the vs2010, But it failed.
so ,what software does you use to compile it?

ps:lm a newbie on language c

**Comment by Bokjan** [comment]
My compiler is **clang**(provided by Xcode), but there's no platform-dependent part, so Visual Studio is ok for building it. Actually, @Hans0924 successfully builded BravoFinder with the latest Visual Studio in late 2016.

It would be easier to give you some further information if you could paste your building system output here.

**Comment by dextercai** [comment]
l try to compile on gcc, but the function of the operating file can't be compiled.

**Comment by Bokjan** [comment]
Cannot figure out your problem. Can you provide more detailed information?

**Comment by dextercai** [comment]
![2017-01-26_092159](https://cloud.githubusercontent.com/assets/12377850/22316561/f41d9426-e3a8-11e6-9be3-1fa02102511c.png)

**Comment by Bokjan** [comment]
Add the **cstdio** header and try again please.

**Comment by dextercai** [comment]
yep, after add the header, it works. thank you very much
非常感谢！:-)
